name: Continuous Integration

env:
  DEVELOPER_DIR: "/Applications/Xcode_13.2.1.app/Contents/Developer"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  xcode-build:
    name: Xcode Build
    runs-on: macos-11
    strategy:
      matrix:

        destination: [
          "platform=macOS",
          "platform=iOS Simulator,name=iPhone 11",
          "platform=tvOS Simulator,name=Apple TV",
          "platform=watchOS Simulator,name=Apple Watch Series 5 - 44mm"
        ]

    steps:
    - uses: actions/checkout@v1
    - name: xcrun xcodebuild build
      run: xcrun xcodebuild build -destination "${{ matrix.destination }}" -project "Differ.xcodeproj" -scheme "Differ"

  xcode-test:
    name: Xcode Test
    runs-on: macos-11
    strategy:
      matrix:
        destination: [
          "platform=macOS",
          "platform=iOS Simulator,name=iPhone 11",
          "platform=tvOS Simulator,name=Apple TV"
        ]

    steps:
    - uses: actions/checkout@v1
    - name: xcrun xcodebuild test
      run: |
        xcrun xcodebuild test -destination "${{ matrix.destination }}" -project "Differ.xcodeproj" -scheme "Differ"
        bash <(curl -s https://codecov.io/bash)

  swift-package-manager-test:
    name: Swift Package Manager
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v1
    - name: swift test
      run: swift test

  cocoapods-verify:
    name: CocoaPods
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v1
    - name: Lint CocoaPods specification
      run: pod lib lint
