name: Create Release

# Create a new release whenever a version is tagged
on:
  release:
    types: [published]

jobs:
  create_release:
    name: Create Release
    runs-on: macos-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Create XCFramework
        uses: unsignedapps/swift-create-xcframework@v2.1.0

      - name: Release XCFramework
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: |
            Differ-*.zip
            Differ-*.sha256
